# Generated by Django 4.2.5 on 2023-09-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В процессе'), ('resolved', 'Решено')], default='new', max_length=15),
        ),
        migrations.AlterField(
            model_name='problem',
            name='priority',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=10),
        ),
    ]
