# Generated by Django 4.2.5 on 2023-10-04 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk_app', '0002_problem_actions_problem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='assigned_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='resolved_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('in_progress', 'in progress'), ('confirmed', 'Confirmed'), ('resolved', 'resolved')], default='new', max_length=15),
        ),
    ]
