# Generated by Django 4.2.5 on 2023-10-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0005_problem_assigned_user_problem_resolved_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='name',
        ),
    ]
